project_id = "ocbmwwulvpexcixywcdj"

[functions.exchange-token]
verify_jwt = false

[functions.webhook-leads]
verify_jwt = false

[functions.webhook-mentoria]
verify_jwt = false

[functions.webhook-vendas]
verify_jwt = false